const rajiniPunchLines: Array<string> = [
	'Kanna, panninga dhan kootama varum. Singam single ah dhan varum',
	'Seeviduven',
	'Idhu epdi iruku?',
	'Mala da. Annamalai',
	'Aandavan solran; Arunachalam mudikran',
	'Naan eppo varuven, epdi varuven nu yaarukkum theriyadhu. Aana vara vendiya nerathuku correct ah varuven',
	'Paraashakti hero da!',
	'Per ah keta odane chumma adhirudhula!',
	'En vazhi thani vazhi, marakkadhinga',
	'Naan oru thadava sonna nooru thadava sonna maari',
	'Vaanavarayan; Kandhavelu vaanavarayan',
	'Enna poosari, indha Vaanavaraayan epdi inga vandhu sendha nu paakringala? Saami konduvandhu sethuduchu.',
	'Kaasu panathukaaga neenga muraiya maathikalam, aana indha Vaanavarayan saamiku kudukra mariyadhaiya evanaalayum maatha mudiyadhu',
	'Modhalla un pulle unakku mariyadha kudukra maari nee nadandhukko. ',
	'Kevalam maalai, mariyadhai, padhavi kaaga thane ivlo kizhthanama nadandhukitta, ippo adha naane unakku tharen',
	'Maalai kaagavum kreedathukkaagauvm ennikume indha vaanavaraayan alanjadhilla',
	'Enna poruthavaraikum, jananga paasam gra maalaiya, eppovo en thozhla potutaanga, anbu ngra mariyadhaya naan avanga mela kaatra varaikum avanga en mela vechrukra mariyadhaiya yaaralayum thadukka mudiyadhu',
	'Panam sampadhikanum nu aasai padravan padhaviya thedi povan. Makkalukku sevai seiyanum nu aasai padravana padhavi thedi varum',
	'20 varushama vaazhkaila engamma nadathuna maraana poraatatha paatha enaku, marana bayame poiduchu',
	'Oorla ellarum enna Bharat uh Bharat uh nu koopduvaanga',
	'Naandhan periyavan nu yarum nenachura koodaadhu. Avanukku appanum porandhiruppan',
	'En manasakshi ku edhira sila kaariyangala senjikittu iruken, idhellam andha koduramana manushanodaiya manasakshi ah thatti ezhupanum ngradhukkaaga dhan',
	'Onnu solren nalla therinjukko. Nallavangala aandavan sodhippan kaivida maaataan. Kettavangalukku aandavan neraya kuduppa aana kaivittuduvaan',
	'Velila sollida maateengale...',
	'Kozhandha, "5 faces". Ennodaya anju mugatha paathen nu sonnela, enakku innoru mugam iruku aarumugam. Indha Padaiyappan oda innoru mugam. Adha nee paakaadha; thaanga maata. Nondhududuva',
	'Enna pathi unakku theiryadhu. En vazhi thani vazhi. Seendaadha',
	`Pombalai na porumai venum; avasarapada koodaadhu. Adakkam venum; aathra pada koodaadhu. Amaidhi venum; adhigaram panna koodaadhu. Kattupaadu venum; ipdi kaththa koodaadhu. Bayabakthi ah irukkanum; ipdi bajari thanam panna koodaadhu.  
	Mothathula pombala pombalaya irukkanum.`,
	'Anger is the cause of all misery. One should know how to control it. Otherwise life will become miserable.',
	'Alavukku adhigama aasa padra aambalayum, adhigama kobapadra pombalayum nalla vaazhndhadha sarithrame kedayadhu',
	'Unga velaya paarunga. Adhan saami',
	'Tamizh padangal la inga maru vechukittu, meesaya murukki kittu, lungi kattikittu, nambiyar uh, "Eh Kabalii" apdinu sonna odane, kuninju sollunga yejaman nu vandhu nippane, andha maari Kabali nu nenachiya da? Kabali da!',
	'25 varushathuku munnala epdi ponaro Kabali apdiye thirumbi vandhuttan nu sollu',
	'Ei! Evanukkavadhu pondaati, kozhandhai kutti nu sentiment gintiment irundha apdiye odi poidu. Kola gaandla iruken. Mavane kollama vida maaten!',
	'Sir avankitta solli veinga "police ah left la vechuko, right la vechuko, straight ah vechukaadhinga" nu',
	'I am a baaad cop',
	'Indha Annamalai podradhu eppome nyaya kanakku. Kooti kalizhichu paaru. Kanakku seriya irukum.',
	'Cool!',
	'Shivaji yum naandhan, MGR um naan dhan',
	'Chumma adhirudhula!',
	'BOSS (Bachelor of Social Service)',
	'Kashta padama edhume kedaikaadhu. Kashta padama kedaikradhu ennikume nilaikaadhu',
	'Koodave porandhadhu. Ennikum pogadhu',
	'Poda! Aandavane namma pakkam irukan',
	'Yaamirukka bayamen! Saravanan irukka bayamen?',
	'I\'ll set your screens on fire',
	'Enna paakra? Original ah ve naan villain ma',
	'Indha vettaikaran kitta endha puliyum paayavum mudiyadhu, padhungavum mudiyadhu',
	'Naan oru dhadava mudivu edutha, adhu mudivu dhan',
	'Naan anbukku kattupaduven; aanavatha kattupaduthuven. Adangama irukanum nu nenaikaravangala adakkuven',
	'Theepetti ku rendu pakkam orasuna dhan thee pudikku. Aana indha Alex Pandiyan uku endha pakkam orasunaalum thee pudikkum',
	'Enakulla thoongi kittirundha singatha thatti ezhupitinga.',
	'Thappenna sariyenna eppodhum vizhayaadu',
	'Baba counting starts',
	'Naan munnukku varadhu dhan unakku prechanai na naan munnukku varuven da. Kaal mela kaal potu ukkaruvenda style ah geth ah',
	'Vengai mavan othaila nikkyan. Dhill irundha mothama vaangale',
	'En kodi parakka vendiya edathula vera evan kodi da parakkum?',
	'Ketta payan sir avan',
	'Naan veezhven endru ninaithaayo?',
	'Indha number 1, number 2 ellam paapa vezhayaatu. I\'m the only one. "Super  one"',
	''
];

export default rajiniPunchLines;